Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Max: 195

Metrics/AbcSize:
  Max: 129

Lint/UselessAssignment:
  Enabled: false

Style/FileName:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false
